# SPDX-License-Identifier: MIT
# Copyright (c) Kirikiri SDL2 Developers

cmake_minimum_required(VERSION 3.12)

if(NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
	message(FATAL_ERROR "The Kirikiri SDL3 plugin stub can only be built on macOS.")
endif()
if(DEFINED CMAKE_SYSTEM_NAME AND NOT CMAKE_SYSTEM_NAME STREQUAL "Darwin")
	message(FATAL_ERROR "The Kirikiri SDL3 plugin stub only supports macOS.")
endif()
if(IOS)
	message(FATAL_ERROR "The Kirikiri SDL3 plugin stub does not support iOS.")
endif()
if(DEFINED CMAKE_OSX_SYSROOT)
	string(TOLOWER "${CMAKE_OSX_SYSROOT}" KRKRSDL3_STUB_OSX_SYSROOT_LOWER)
	if(KRKRSDL3_STUB_OSX_SYSROOT_LOWER MATCHES "iphone|appletv|watch")
		message(FATAL_ERROR "The Kirikiri SDL3 plugin stub requires the macOS SDK.")
	endif()
endif()
if(NOT DEFINED CMAKE_OSX_ARCHITECTURES OR CMAKE_OSX_ARCHITECTURES STREQUAL "")
	set(CMAKE_OSX_ARCHITECTURES "arm64" CACHE STRING "Supported macOS architecture" FORCE)
endif()
list(LENGTH CMAKE_OSX_ARCHITECTURES KRKRSDL3_STUB_ARCH_COUNT)
if(NOT KRKRSDL3_STUB_ARCH_COUNT EQUAL 1 OR NOT CMAKE_OSX_ARCHITECTURES STREQUAL "arm64")
	message(FATAL_ERROR "The Kirikiri SDL3 plugin stub only supports arm64.")
endif()
if(NOT DEFINED CMAKE_OSX_DEPLOYMENT_TARGET OR CMAKE_OSX_DEPLOYMENT_TARGET STREQUAL "")
	set(CMAKE_OSX_DEPLOYMENT_TARGET "13.0" CACHE STRING "Minimum supported macOS version" FORCE)
endif()
if(NOT CMAKE_OSX_DEPLOYMENT_TARGET MATCHES "^[0-9]+(\\.[0-9]+)*$")
	message(FATAL_ERROR "CMAKE_OSX_DEPLOYMENT_TARGET must be a macOS version number.")
endif()
if(CMAKE_OSX_DEPLOYMENT_TARGET VERSION_LESS "13.0")
	message(FATAL_ERROR "The Kirikiri SDL3 plugin stub requires macOS 13.0 or later.")
endif()

project(tp_stub_krkrsdl3 LANGUAGES CXX)

if(NOT APPLE OR NOT CMAKE_SYSTEM_NAME STREQUAL "Darwin")
	message(FATAL_ERROR "The Kirikiri SDL3 plugin stub only supports macOS.")
endif()

add_library(tp_stub STATIC)
set_target_properties(tp_stub PROPERTIES CXX_STANDARD 11)
set_target_properties(tp_stub PROPERTIES POSITION_INDEPENDENT_CODE TRUE)
target_sources(tp_stub PRIVATE tp_stub.cpp)
target_include_directories(tp_stub PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
